name: 'C++ Build on Arch'

on: [push, pull_request]

permissions:
  contents: write

jobs:
  Linux-build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update Arch Linux and install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm base-devel cmake boost boost-libs git

      - name: Configure CMake
        run: cmake . -DPROJECT_VERSION="0.0.${{ github.run_number }}"

      - name: Build project
        run: cmake --build .

      - name: Run tests
        run: cmake --build . --target test

      - name: Create package
        run: |
          cpack -G TGZ -C Release

      - name: List files
        run: |
            ls -la *.tar.gz || echo "No .tar.gz files found"

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            *.tar.gz

      - name: Create Release and Upload Asset
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: v0.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
                *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
