name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      
      
      - name: Configure CMake
        run: cmake . -DPATCH_VERSION="0.0.${{ github.run_number }}"
      
      - name: Build project
        run: cmake --build .
      
      - name: Run tests
        run: cmake --build . --target test
      
      - name: Create package
        run: cmake --build . --target package

      
      - name: Create Release and Upload Asset
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Release v0.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: ./helloworld-0.0.${{ github.run_number }}-Win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
