name: 'Build C++ Project with Boost (manual install + cache)'

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Boost
        uses: actions/cache@v4
        with:
          path: C:\local\boost_build
          key: ${{ runner.os }}-boost-1.84.0
          restore-keys: |
            ${{ runner.os }}-boost-

      - name: Download and Build Boost
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -L -o boost.zip https://archives.boost.io/release/1.84.0/source/boost_1_84_0.zip
          7z x boost.zip -oC:\local\
          cd C:\local\boost_1_84_0
          bootstrap.bat
          b2 install --prefix=C:\local\boost_build

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DBOOST_ROOT="C:/local/boost_build"

      - name: Build Project
        run: |
          cd build
          cmake --build . --config Release
