name: 'Build C++ Project with Boost (choco)'

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Boost via Chocolatey
        run: choco install boost-msvc-14.3 -y

       - name: Configure CMake (Release)
        run: |
          mkdir build
          cd build
          cmake .. `
            -DCMAKE_BUILD_TYPE=Release `
            -DPROJECT_VERSION="0.0.${{ github.run_number }}" `
            -DBUILD_TESTING=OFF  # Отключаем тесты

      - name: Build Release
        run: |
          cd build
          cmake --build . --config Release

      - name: Create standalone package
        run: |
          cd build/Release
          # Проверяем что exe файл работает без зависимостей
          .\helloworld_cli.exe --version || echo "Executable might have dependencies"
          # Создаем ZIP
          powershell "Compress-Archive -Path *.exe -DestinationPath ../helloworld-0.0.${{ github.run_number }}-win64.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Windows-Release v0.0.${{ github.run_number }}-win64
          name: Windows Release v0.0.${{ github.run_number }}
          files: build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
